# Generated by Django 6.0.3 on 2026-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationrequest",
            name="is_emergency_broadcast",
            field=models.BooleanField(default=False),
        ),
    ]
