# Generated by Django 4.2.7 on 2026-03-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_available', models.PositiveIntegerField()),
                ('units_reserved', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(db_index=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='bloodbanks.bloodbank')),
            ],
            options={
                'indexes': [models.Index(fields=['bloodbank', 'blood_group'], name='inventory_i_bloodba_3d30e6_idx'), models.Index(fields=['expiry_date'], name='inventory_i_expiry__faeaca_idx')],
            },
        ),
    ]
