# Generated by Django 4.2.7 on 2026-03-06 08:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('units_reserved', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField(db_index=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('batch_code', models.CharField(blank=True, help_text='Optional batch identifier', max_length=50)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='bloodbanks.bloodbank')),
            ],
            options={
                'indexes': [models.Index(fields=['bloodbank', 'blood_group'], name='inventory_i_bloodba_3d30e6_idx')],
            },
        ),
    ]
