# Generated by Django 6.0.3 on 2026-04-10 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloodbanks", "0001_initial"),
        ("donors", "0002_delete_notification"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="bloodbank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloodbanks.bloodbank",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="donors.donor",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("EMERGENCY", "Emergency"),
                    ("STATUS_UPDATE", "Status Update"),
                    ("SYSTEM", "System"),
                    ("SHORTAGE", "Shortage Alert"),
                    ("ELIGIBLE", "Eligibility Reminder"),
                    ("CAMPAIGN", "Donation Camp"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
