# Generated by Django 4.2.7 on 2026-03-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('storage_capacity', models.IntegerField(help_text='Maximum units the bank can store')),
                ('component_separation_available', models.BooleanField(default=False)),
                ('operational_status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloodbank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
