# Generated by Django 4.2.7 on 2026-03-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('eligibility_status', models.CharField(default='New Donor', max_length=20)),
                ('preferred_bloodbank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbanks.bloodbank')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SHORTAGE', 'Shortage Alert'), ('ELIGIBLE', 'Eligibility Reminder'), ('CAMPAIGN', 'Donation Camp')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('bloodbank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbanks.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('donation_date', models.DateField()),
                ('units', models.IntegerField(default=1)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('bloodbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbanks.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor')),
            ],
        ),
    ]
