# Generated by Django 6.0.3 on 2026-04-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
